# Generated by Django 4.0 on 2021-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('ProCod', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de profesión')),
                ('ProDes', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Profesiones',
            },
        ),
    ]
