# Generated by Django 3.2 on 2021-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Imagen de profesión'),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='ProDes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripción'),
        ),
    ]
