# Generated by Django 3.2 on 2021-12-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0003_auto_20211211_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='id',
        ),
        migrations.AddField(
            model_name='profesion',
            name='auto_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
