# Generated by Django 3.2.5 on 2021-12-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0005_auto_20211211_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='ProCod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Profesión'),
        ),
    ]
