# Generated by Django 3.2.5 on 2021-12-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0006_alter_profesion_procod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='ProDes',
            field=models.CharField(max_length=30, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='img',
            field=models.ImageField(upload_to='pics', verbose_name='Imagen de profesión'),
        ),
    ]
