# Generated by Django 3.2.5 on 2021-12-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0007_auto_20211211_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='ProDes',
        ),
    ]
