# Generated by Django 4.0 on 2021-12-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('EspCod', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de la especialidad')),
                ('EspDes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('EspProCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesiones.profesion', verbose_name='Profesion')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
    ]
