# Generated by Django 3.2.5 on 2021-12-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioprofesional',
            name='UsuProPun',
            field=models.IntegerField(default=0, verbose_name='Puntuacion'),
        ),
    ]
