# Generated by Django 3.2.5 on 2021-12-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distritos', '0001_initial'),
        ('provincias', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('usuarios', '0002_usuarioprofesional_usupropun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarionormal',
            name='UsuNorDepCod',
            field=models.ForeignKey(default='04', on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuarionormal',
            name='UsuNorDisCod',
            field=models.ForeignKey(default='040128', on_delete=django.db.models.deletion.CASCADE, to='distritos.distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='usuarionormal',
            name='UsuNorProvCod',
            field=models.ForeignKey(default='0401', on_delete=django.db.models.deletion.CASCADE, to='provincias.provincia', verbose_name='Provincia'),
        ),
    ]
