# Generated by Django 3.2.5 on 2021-12-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0008_remove_profesion_prodes'),
        ('departamentos', '0001_initial'),
        ('distritos', '0001_initial'),
        ('provincias', '0001_initial'),
        ('usuarios', '0003_auto_20211212_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioprofesional',
            name='UsuProCal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='usuarioprofesional',
            name='UsuProDepCod',
            field=models.ForeignKey(default='04', on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuarioprofesional',
            name='UsuProDisCod',
            field=models.ForeignKey(default='040128', on_delete=django.db.models.deletion.CASCADE, to='distritos.distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='usuarioprofesional',
            name='UsuProProCod',
            field=models.ForeignKey(default='VET', on_delete=django.db.models.deletion.CASCADE, to='profesiones.profesion', verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='usuarioprofesional',
            name='UsuProProvCod',
            field=models.ForeignKey(default='0401', on_delete=django.db.models.deletion.CASCADE, to='provincias.provincia', verbose_name='Provincia'),
        ),
    ]
