# Generated by Django 3.2 on 2021-12-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesiones', '0001_initial'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='PubDes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='PubProfCod',
            field=models.ForeignKey(default='ELE', on_delete=django.db.models.deletion.CASCADE, to='profesiones.profesion', verbose_name='Especialidad'),
            preserve_default=False,
        ),
    ]
