# Generated by Django 3.2 on 2021-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_auto_20211210_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='PubDes',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='PubFecIni',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='PubProfCod',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='PubUsuNorCod',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Apellidos',
            field=models.CharField(default='texto', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Celular',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Correo',
            field=models.EmailField(default='nombre@gmail.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Descripcion',
            field=models.TextField(default='texto', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Distrito',
            field=models.CharField(choices=[('Alto Selva Alegre', 'Alto Selva Alegre'), ('Arequipa', 'Arequipa'), ('Cayma', 'Cayma'), ('Cerro Colorado', 'Cerro Colorado'), ('Characato', 'Characato'), ('Chiguata', 'Chiguata'), ('Jacobo Hunter', 'Jacobo Hunter'), ('Jose Luis Bustamante Y Rivero', 'Jose Luis Bustamante Y Rivero'), ('La Joya', 'La Joya'), ('Mariano Melgar', 'Mariano Melgar'), ('Miraflores', 'Miraflores'), ('Mollebaya', 'Mollebaya'), ('Paucarpata', 'Paucarpata'), ('Pocsi', 'Pocsi'), ('Polobaya', 'Polobaya'), ('Quequeña', 'Quequeña'), ('Sabandia', 'Sabandia'), ('Sachaca', 'Sachaca'), ('San Juan De Siguas', 'San Juan De Siguas'), ('San Juan De Tarucani', 'San Juan De Tarucani'), ('Santa Isabel De Siguas', 'Santa Isabel De Siguas'), ('Santa Rita De Sihuas', 'Santa Rita De Sihuas'), ('Socabaya', 'Socabaya'), ('Tiabaya', 'Tiabaya'), ('Uchumayo', 'Uchumayo'), ('Vitor', 'Vitor'), ('Yanahuara', 'Yanahuara'), ('Yarabamba', 'Yarabamba'), ('Yura', 'Yura')], default='', max_length=90),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='EstadoTrabajo',
            field=models.CharField(choices=[('Activo', 'Estado Activo'), ('En Proceso', 'Estado Ocupado'), ('Culminado', 'Estado Terminado')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Nombres',
            field=models.CharField(default='texto', max_length=25),
            preserve_default=False,
        ),
    ]
