# Generated by Django 3.2.5 on 2021-12-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_auto_20211211_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='IdDeUsuario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
