# Generated by Django 3.2.5 on 2021-12-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_publicacion_iddeusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='IdDeUsuario',
        ),
    ]
