# Generated by Django 4.0 on 2021-12-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        ('provincias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('DisCod', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código de distrito')),
                ('DisNom', models.CharField(max_length=50, verbose_name='Descripción')),
                ('DisDepCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento', verbose_name='Departamento')),
                ('DisProvCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provincias.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name_plural': 'Distritos',
                'unique_together': {('DisDepCod', 'DisProvCod', 'DisCod')},
            },
        ),
    ]
